### ISSUE TITLE
Missing bubble & snow CSS source maps

### ISSUE THREAD

**Issue by davidromani** [Ehyiah/ux-quill#36]
Hi 👋

Just included this bundle into my project and I've discovered this 404 respones in the browser's console.

```
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (quill.bubble.css.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (quill.snow.css.map, line 0)
```

**Comment by Ehyiah** [comment]
Hello, sorry for the long delay, had no free time these past few months.
Is the issue still valid ? 
Can you tell me what are you using ? AssetMapper or webpack ? 

Cause in AssetMapper requirements, these assets are presents. 

`            "quill/dist/quill.snow.css": "2.0.2",
            "quill/dist/quill.bubble.css": "2.0.2",
`

And I got no problems while using the bundle in my projects.

**Comment by davidromani** [comment]
> Hello, sorry for the long delay, had no free time these past few months. Is the issue still valid ? Can you tell me what are you using ? AssetMapper or webpack ?

AssetMapper

**Comment by Ehyiah** [comment]
And if you take a look inside importmap.php don't you see these lines ? 

`
    'quill/dist/quill.snow.css' => [
        'version' => '2.0.2',
        'type' => 'css',
    ],
    'quill/dist/quill.bubble.css' => [
        'version' => '2.0.2',
        'type' => 'css',
    ],
`

I just tried before replying a reinstall of the bundle in one of my project, and these lines were added in importmap.php

**Comment by Ehyiah** [comment]
closing issue as last response was in december

**Comment by davidromani** [comment]
@Ehyiah apologies about my delay.

Even with the latest 3.0.1 version installed and confirmed this importmap config:

```php
    'quill' => [
        'version' => '2.0.3',
    ],
    'quill/dist/quill.snow.css' => [
        'version' => '2.0.3',
        'type' => 'css',
    ],
    'quill/dist/quill.bubble.css' => [
        'version' => '2.0.3',
        'type' => 'css',
    ],
    // and many more Quill dependencies...
```

Still showing this browser console error log:

```
[Error] Failed to load resource: the server responded with a status of 404 () (quill.bubble.css.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 () (quill.bubble.css.map, line 0)
```

**Comment by davidromani** [comment]
Safari v18.5 on macOS 14.7

Is not a problem, it works perfects, is only to avoid unnecessary not found requests.

**Comment by INFOTECH974** [comment]
I'm having the same issue. And it's causing critical errors, because I'm logging all errors (regardless of the error code—404, 500, etc.) using Posthog. I'm using AssetMapper. However, if I remove the following from both CSS files (Quill vendor), the error goes away (which makes sense):

/*# sourceMappingURL=quill.bubble.css.map*/
/*# sourceMappingURL=quill.snow.css.map*/

**Comment by Ehyiah** [comment]
Hi, I think I just found the issue.
Please try the 3.6.1 release, the css source maps where missing from assetMapper autoimport.

**Comment by INFOTECH974** [comment]
Hello,

I'm following up on this issue because it didn't actually solve the problem. I just reinstalled it on a new client project, and in my logs, I'm seeing the same issue:


```log
'request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: Asset with public path '/assets/vendor/quill/dist/quill.snow.css.map' not found. [...]'
'request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: Asset with public path '/assets/vendor/quill/dist/quill.bubble.css.map' not found. [...]'
```

The problem is that when I do this with Asset Mapper, it doesn’t actually download the .map file:

```js
'quill/dist/quill.snow.css' => ['version' => '2.0.3', 'type' => 'css'], // OK
'quill/dist/quill.snow.css.map' => ['version’ => '2.0.3'], // NOT OK
'quill/dist/quill.bubble.css' => [‘version’ => '2.0.3', 'type' => 'css'], // OK
'quill/dist/quill.bubble.css.map' => ['version' => '2.0.3'], // NOT OK
```

If we analyze the two .map files, AssetMapper concatenates the file with a .js, so it doesn’t actually link the .map, and more importantly, in the js file we can see this:

```js
Failed to bundle using Rollup v2.79.2. If you believe this to be an issue with jsDelivr, and not with the package itself [...]. // quill/dist/quill.snow.css.map or quill/dist/quill.bubble.css.map
```

The problem doesn’t actually stem from this bundle, but rather from AssetMapper.

By the way, I also saw this in the logs, which means that AssetMapper automatically added '/+esm” at the end, causing the 'Failed to bundle...” error:

```
[2026-06-04T10:30:37.280475+04:00] http_client.INFO: Request: 'GET https://cdn.jsdelivr.net/npm/quill@2.0.3/dist/quill.snow.css.map/+esm” [] []
[2026-06-04T10:30:37.283427+04:00] http_client.INFO: Request: 'GET https://cdn.jsdelivr.net/npm/quill@2.0.3/dist/quill.bubble.css.map/+esm” [] []
```

For now, I've worked around this as follows to avoid having events automatically triggered on the Posthog side (or other systems):

```yaml
# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: ‘%env(APP_SECRET)%’

    # Note that the session will be started ONLY if you read or write from it.
    session: true

   # EXACTLY HERE, I CHANGE THE LOG LEVEL TO DEBUG TO AVOID ERROR
    exceptions:
        Symfony\Component\HttpKernel\Exception\NotFoundHttpException:
            log_level: debug

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
```
